# Generated by Django 4.2.6 on 2023-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ROUTER', 'Reititin'), ('SWITCH', 'Kytkin'), ('NAS', 'NAS'), ('ePDU', 'ePDU'), ('PROXMOX', 'Proxmox')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('admin_link', models.URLField()),
            ],
        ),
    ]
