# Generated by Django 4.2.6 on 2023-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallintaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
