# Generated by Django 4.2 on 2023-10-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallintaapp', '0002_device_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='admin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
